#!/usr/bin/env python3
"""Gives every AFFIX its own address, and quotes the book at it.

THE PROBLEM. Ido builds its vocabulary by derivation, and the Dicionario
holds only the ROOTS: kovrilo, skribilo, dometo, hundino are none of them
headwords, and 9473 articles will not yield one of them. What yields them
is the affix, and the affix lives in SUFIXI -- 89 kB of continuous prose.
So the cheapest question the site can be asked, « what does -il- do », cost
90 kB, and the reader had to find the right paragraph inside it.

WHAT THIS WRITES. One file per affix, holding THE BOOK'S OWN PARAGRAPHS on
it, verbatim, from the head that opens it to the head that opens the next.
60 affixes: 38 suffixes, 19 prefixes, 3 technical prefixes. No rule of
grammar is composed here -- this is the discipline of temi.py, applied to
a division the book itself makes.

WHY IT NEEDS NO SEARCH TERMS, AND temi.py DOES. temi.py collects topics
that CROSS the chapters and must therefore search for them, which is an
editorial act it prints. An affix does not cross anything: Beaufront opens
its discussion with the affix in bold, a full stop and a dash -- « **-ach-.**
— Ta sufixo... » -- and closes it by opening the next. The division is the
book's, and the tool only follows it.

THE HEAD IS NOT ALWAYS SET THE SAME WAY, AND THAT COST FIVE AFFIXES.

  * The FULL STOP falls inside the bold in most of the book -- « **-ach-.**
    — » -- and OUTSIDE it in five places: « **-ar-**. — », and the same for
    -atr-, -e-, -ebl- and -ind-. A pattern admitting only the first form
    reports 55 affixes and looks right, and among the five it silently
    drops are -EBL- AND -IND-, which are two of the most used suffixes in
    the language. The stop is therefore admitted on either side.
  * The technical prefixes carry an EXTRA ASTERISK -- « ***equi-.** »
    against « **mono-.** » -- because the transcription sets them in italic
    as well as bold. Admitting only two asterisks finds mono- and loses
    equi- and ko-, which is two thirds of that chapter.

The dash is what keeps the pattern honest: paragraphs open with a bold word
often enough -- « **Parolo** esas frazo », « **Posiblo** = ... » -- and none
of them carries the dash that follows an affix.

THE INDEX LINE IS MECHANICAL. Form, the chapter it stands in, the first
example the book prints under it, and the file's weight. The example is the
first bold run of the body, LIFTED, not chosen: nothing here is a gloss
this project wrote.

    python3 tools/afixi.py

Run it after tools/machine_readable.py: it reads chapitri/, which that
script writes.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHAPTERS = ROOT / 'chapitri'
OUT = ROOT / 'afixi'
SITE = 'https://ido.help/gramatiko/'

HEADER = '<!-- Generated by tools/afixi.py from chapitri/. Do not edit. -->'

# The affix in bold -- two asterisks, or three where the transcription sets
# it in italic too -- then a full stop, then the book's dash. Anchored to
# the start of a line, which is where a paragraph begins.
HEAD = re.compile(r'^\*{2,3}(-?[^\s*]+?)\.?\*\*\.?\s*[—–]\s', re.M)

# The first bold run of a body, which is the first example the book prints.
EXAMPLE = re.compile(r'\*\*([^*]+?)\*\*')

SOURCES = [
    ('sufixi', 'sufixo'),
    ('prefixi', 'prefixo'),
    ('prefixi-teknikala', 'prefixo teknikala'),
]


def sections(text):
    """The chapter cut at its affix heads: (affix, the whole passage)."""
    marks = list(HEAD.finditer(text))
    for i, m in enumerate(marks):
        end = marks[i + 1].start() if i + 1 < len(marks) else len(text)
        yield m.group(1), text[m.start():end].strip()


# BEAUFRONT MARKS HIS OWN EXAMPLES. « Ex. : » is his abbreviation, and what
# follows it is the example, in whatever emphasis he happened to set it --
# bold under -il- (**pektilo**), italic under bi (*biciklo*), and no
# emphasis at all under -iz- (Ex. : armizar). A rule keyed to BOLD finds
# the first two and loses the third: 5 of the 60 affixes came out with no
# example at all that way, among them anti, auto and bi.
MARK = re.compile(r'Ex\.\s*:\s*')
ITALIC = re.compile(r'(?<!\*)\*([^*]+?)\*(?!\*)')

# The endings of Ido: the substantive, the adjective, the adverb, the
# plural, the three infinitives and the tenses. A suffix is followed by one
# of these, or the word is not a derivation.
ENDINGS = {'', 'o', 'a', 'e', 'i', 'ar', 'ir', 'or',
           'as', 'is', 'os', 'us', 'ez'}


def first_example(affix, kind, body):
    """The first example the book itself prints under an affix.

    Not the first bold run: that is the head, or -- under -ach- -- « ac »,
    the form the Committee REFUSED, which as an example of what the affix
    does is worse than nothing.

    The candidate must carry the affix's letters and be longer than them,
    and it must carry them WHERE THE AFFIX GOES: a suffix's example does
    not begin with it, or « -uro » answers for -ur- and the affix becomes
    its own example; a prefix's example does begin with it.
    """
    core = affix.strip('-').lower()
    head = HEAD.match(body)
    rest = body[head.end():] if head else body
    mark = MARK.search(rest)
    # WHERE THERE IS NO « Ex. : » -- 7 affixes of the 60, among them -ach-,
    # bo- and mi- -- fall back to the BOLD runs, and to those alone. Falling
    # back to the running prose instead put « Germana » under ge- and
    # « Parvenü » under par-: both are words the paragraph DISCUSSES, and
    # neither is an example of the affix.
    regions = ([rest[mark.end():]] if mark else [])
    regions.append(' , '.join(EXAMPLE.findall(rest)))
    # AND LAST THE ITALIC. -ism-, -eg- and auto set their examples in
    # italic and nowhere else -- « *Kristanismo* », « *granda* » -- so a
    # rule stopping at bold leaves those three blank. Italic also carries
    # the glosses and the foreign words Beaufront cites, which is why it
    # comes last and why the affix-in-the-right-place test still applies.
    regions.append(' , '.join(ITALIC.findall(rest)))
    for text in regions:
        for word in re.split(r'[,;:()\s]|\s—\s', text):
            word = word.replace('*', '').strip(' .,;:!?—–«»\n')
            bare = word.strip('-').lower()
            if ' ' in word or not bare.replace('-', '').isalpha():
                continue
            if bare == core or len(bare) <= len(core) or core not in bare:
                continue
            # A SUFFIX SITS IMMEDIATELY BEFORE THE GRAMMATICAL ENDING --
            # that is the book's own rule of derivation -- so what follows
            # it in an example is an ending and nothing else. Without this
            # test « Franca » answered for -an-: the letters are in it, in
            # the middle, and the word is not a derivation at all.
            if kind.startswith('sufixo'):
                if bare.startswith(core):
                    continue
                if bare[bare.rfind(core) + len(core):] not in ENDINGS:
                    continue
            if kind.startswith('prefixo') and not bare.startswith(core):
                continue
            return word
    return ''


def main():
    OUT.mkdir(exist_ok=True)
    for old in OUT.glob('*.md'):
        old.unlink()

    rows = []
    for stem, kind in SOURCES:
        source = (CHAPTERS / f'{stem}.md').read_text('utf-8')
        for affix, body in sections(source):
            page = '\n'.join([
                HEADER, '',
                f'# {affix}', '',
                f'Ek *Kompleta Gramatiko Detaloza di la Linguo Internaciona '
                f'Ido*, L. de Beaufront, 1925 — chapitro '
                f'[{stem.upper().replace("-", " ")}]({SITE}chapitri/'
                f'{stem}.md).',
                f'Transskribita de {SITE}', '',
                f'Ico esas la texto dil libro ipsa, sen chanjo. Nula reguli '
                f'esas skribita hike.', '',
                '---', '', body, ''])
            (OUT / f'{affix}.md').write_text(page, 'utf-8')
            rows.append({
                'afixo': affix, 'speco': kind, 'chapitro': stem,
                'exemplo': first_example(affix, kind, body),
                'okteti': len(page.encode('utf-8')),
            })

    table = [HEADER, '',
             '# Afixi', '',
             'L. de Beaufront, *Kompleta Gramatiko Detaloza di la Linguo '
             'Internaciona Ido*, Esch-Alzette, Meier-Heucke, 1925.', '',
             f'Transskribita de {SITE}', '',
             f'La {len(rows)} afixi dil linguo, singla en sua propra dosiero, '
             'kun la texto dil libro ipsa pri ol. La Dicionario donas nur la '
             'RADIKI : *kovrilo*, *skribilo*, *dometo*, *hundino* ne esas '
             'vedvorti, e li lektesas de lia radiko ed de ica pagini.', '',
             'La grandeso esas indikata por ke on povez selektar ANTE '
             'deskargar. La exemplo esas la unesma quan la libro printas.', '',
             '| afixo | speco | exemplo | grandeso |',
             '| --- | --- | --- | ---: |']
    for r in rows:
        table.append(f'| [{r["afixo"]}]({r["afixo"]}.md) | {r["speco"]} | '
                     f'{r["exemplo"]} | {r["okteti"] // 1024 or 1} Ko |')
    (OUT / 'index.md').write_text('\n'.join(table) + '\n', 'utf-8')

    for _, kind in SOURCES:
        n = sum(1 for r in rows if r['speco'] == kind)
        print(f'  {n:3d} {kind}')
    total = sum(r['okteti'] for r in rows)
    print(f'  {len(rows)} afixi, {total:,} bytes, '
          f'{total // len(rows):,} on average')


if __name__ == '__main__':
    main()
