#!/usr/bin/env python3
"""Draws from the Gramatiko its MACHINE-READABLE versions.

WHY. The page weighs 1.2 MB for 467 kB of text: the rest is markup and
284 kB of inline CSS. Whoever wants to READ the grammar -- an indexing
robot, a crawler, a language model -- therefore pays two and a half times
the price of the text, and still has to dig it out.

The split BY CHAPTER is the essential part. A grammar is not read end to
end: one looks up a point in it. Whoever wants to know how the plural is
formed does not have to load all fifty chapters. That is where the saving
is made, far more than in compression.

  gramatiko.md          the whole book, in one piece.
  chapitri/<name>.md    one file per chapter.
  chapitri/index.md     the table, with each one's size: enough to choose
                        BEFORE downloading.

Generated, never edited by hand. The source stays index.html.

    python3 tools/machine_readable.py
"""

import os
import re
import sys
from pathlib import Path

# THIS DIRECTORY CARRIES ITS OWN "html.py". Since the script is launched
# from tools/, that file comes FIRST on the search path and shadows the
# standard module of the same name. We therefore remove the script's
# directory before importing, failing which "html.unescape" does not exist.
sys.path[:] = [d for d in sys.path
               if os.path.abspath(d) != os.path.dirname(os.path.abspath(__file__))]
import html as modul_html  # noqa: E402
from html.parser import HTMLParser  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
CHAPTERS = ROOT / 'chapitri'

HEADER = '<!-- Generated by tools/machine_readable.py from index.html. Do not edit. -->\n'
SOURCE_LINE = 'Transskribita de https://ido.help/gramatiko/\n'


def as_markdown(h: str) -> str:
    """A fragment of HTML as Markdown.

    The folio marks go: they are anchors into the PDF, of no value to
    whoever reads the text. Italic and bold stay -- in a grammar they
    distinguish the example from the rule, and that distinction carries
    meaning.
    """
    h = re.sub(r'<a[^>]*class="fol"[^>]*>.*?</a>', '', h, flags=re.S)
    h = re.sub(r'<i>(.*?)</i>', r'*\1*', h, flags=re.S)
    h = re.sub(r'<em>(.*?)</em>', r'*\1*', h, flags=re.S)
    h = re.sub(r'<b>(.*?)</b>', r'**\1**', h, flags=re.S)
    h = re.sub(r'<strong>(.*?)</strong>', r'**\1**', h, flags=re.S)
    h = re.sub(r'<br\s*/?>', '  \n', h)
    h = re.sub(r'<[^>]+>', '', h)
    h = modul_html.unescape(h)
    h = re.sub(r'[ \t ]+', ' ', h)
    return re.sub(r' *\n *', '\n', h).strip()


class BlockCollector(HTMLParser):
    """Gathers the body's top-level blocks: headings, paragraphs, notes.

    NO REGULAR EXPRESSION IS USED HERE, and that is deliberate: a paragraph
    may contain a table, a group, a list -- hence other "div"s. A regular
    expression looking for the closing "/div" counts one too many or one
    too few as soon as the nesting varies, and that is exactly what lost
    one paragraph in 1230. A parser counts the depth; it cannot go wrong.
    """

    SPECOJ = ('tit', 'p', 'noto')

    def __init__(self):
        super().__init__(convert_charrefs=False)
        self.blocks = []
        self.current = None
        self.profundo = 0
        self.pieces = []

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        klaso = (a.get('class') or '').split()
        if self.current is None and tag == 'div' and klaso and klaso[0] in self.SPECOJ:
            self.current = {'kind': klaso[0], 'ch': a.get('data-ch'), 'id': a.get('id')}
            self.profundo = 1
            self.pieces = []
            return
        if self.current is not None:
            if tag == 'div':
                self.profundo += 1
            self.pieces.append(self.get_starttag_text() or '')

    def handle_endtag(self, tag):
        if self.current is None:
            return
        if tag == 'div':
            self.profundo -= 1
            if self.profundo == 0:
                self.current['text'] = as_markdown(''.join(self.pieces))
                self.blocks.append(self.current)
                self.current = None
                return
        self.pieces.append('</%s>' % tag)

    def handle_startendtag(self, tag, attrs):
        if self.current is not None:
            self.pieces.append(self.get_starttag_text() or '')

    def handle_data(self, d):
        if self.current is not None:
            self.pieces.append(d)

    def handle_entityref(self, n):
        if self.current is not None:
            self.pieces.append('&%s;' % n)

    def handle_charref(self, n):
        if self.current is not None:
            self.pieces.append('&#%s;' % n)


def blocks_of(s: str) -> list:
    """Walks the body and returns the run of blocks, in the book's order.

    The order IS the structure of the book: a note must stay where the
    author put it, and a paragraph under the heading that governs it.
    """
    body = re.search(r'<main\b.*?</main>', s, re.S)
    k = BlockCollector()
    k.feed(body.group(0) if body else s)
    return k.blocks


def chapter_title(t: str) -> str:
    """A chapter's title, brought back to one line and stripped.

    The book sets its headings in bold; "texto" renders that bold
    faithfully as asterisks. In a Markdown TITLE they have no place -- the
    title is already a title -- and in the table they would be seen spelled
    out inside the link. We take them off.
    """
    t = re.sub(r'\*{1,2}(.*?)\*{1,2}', r'\1', t)
    t = re.sub(r'\s+', ' ', t).strip()
    return t.rstrip('.').strip() or t


def main() -> None:
    s = (ROOT / 'index.html').read_text(encoding='utf-8')
    blocks = blocks_of(s)

    # Group by chapter, keeping the order.
    chapters, current = [], None
    for b in blocks:
        if b['kind'] == 'tit':
            current = {'id': b['id'], 'title': chapter_title(b['text']), 'blocks': []}
            chapters.append(current)
        elif current is not None:
            current['blocks'].append(b)

    CHAPTERS.mkdir(exist_ok=True)
    for stale in CHAPTERS.glob('*.md'):
        stale.unlink()

    def body_of(c):
        lines = []
        for b in c['blocks']:
            if not b['text']:
                continue
            lines.append(('> ' + b['text'].replace('\n', '\n> ')) if b['kind'] == 'noto'
                       else b['text'])
        return '\n\n'.join(lines)

    # One file per chapter.
    table = []
    for c in chapters:
        body = body_of(c)
        path = CHAPTERS / f'{c["id"]}.md'
        path.write_text(
            f'{HEADER}\n# {c["title"]}\n\n'
            f'Ek *Kompleta Gramatiko Detaloza di la Linguo Internaciona Ido*, '
            f'L. de Beaufront, 1925.\n{SOURCE_LINE}\n---\n\n{body}\n',
            encoding='utf-8')
        table.append((c['id'], c['title'], path.stat().st_size,
                       len(c['blocks'])))

    # The table, with the sizes: choose before downloading.
    lines = [HEADER, '# Kompleta Gramatiko — chapitri\n',
           'L. de Beaufront, *Kompleta Gramatiko Detaloza di la Linguo '
           'Internaciona Ido*, Esch-Alzette, Meier-Heucke, 1925.\n', SOURCE_LINE,
           'Singla chapitro esas apartra dosiero. La grandeso esas indikata '
           'por ke on povez selektar ANTE deskargar.\n',
           '| chapitro | titolo | alinei | grandeso |',
           '| --- | --- | ---: | ---: |']
    for i, (cid, title, size, n) in enumerate(table, 1):
        lines.append(f'| {i} | [{title}]({cid}.md) | {n} | {size // 1024 or 1} Ko |')
    (CHAPTERS / 'index.md').write_text('\n'.join(lines) + '\n', encoding='utf-8')

    # The whole book.
    whole = [HEADER, '# Kompleta Gramatiko Detaloza di la Linguo Internaciona Ido\n',
            'L. de Beaufront · Esch-Alzette, Meier-Heucke, 1925 · '
            f'{len(chapters)} chapitri\n', SOURCE_LINE, '---\n']
    for c in chapters:
        whole.append(f'## {c["title"]}\n')
        whole.append(body_of(c) + '\n')
    (ROOT / 'gramatiko.md').write_text('\n'.join(whole), encoding='utf-8')

    print(f'  {len(chapters)} chapters, {len(blocks)} blocks')
    print(f'  gramatiko.md      {(ROOT / "gramatiko.md").stat().st_size:>9,} bytes')
    mean = sum(t[2] for t in table) // max(len(table), 1)
    print(f'  chapitri/         {len(table)} files, {mean:,} bytes on average, '
          f'largest {max(t[2] for t in table):,}')


if __name__ == '__main__':
    main()
