#!/usr/bin/env python3
"""Gives every grammatical TOPIC an address, and cites the book by its own
paragraph numbers.

THE PROBLEM. The Gramatiko is split by chapter, which answers "how is the
plural formed" -- there is a chapter called LA PLURALO EN IDO. It does not
answer "what does the 1925 grammar say about the -n ending", because THERE
IS NO CHAPTER ABOUT IT. The discussion is spread over SINTAXO, VORTORDINO,
PERSONAL PRONOMI and ADVERBI, and nothing in the book or on the site points
at those four places together. A topic that cuts across chapters has no
address, and what has no address cannot be fetched -- only guessed at.

WHAT THIS WRITES. One file per cross-cutting topic, holding THE BOOK'S OWN
PARAGRAPHS, verbatim, each cited by the number the book itself prints. No
sentence of grammar is composed here. The editorial act -- and it is one --
is the choice of search terms, which is therefore PRINTED IN EVERY FILE so
that a reader can see what was searched for and judge it.

WHY THE PARAGRAPH NUMBER IS THE CITATION. Beaufront numbered his paragraphs
1 to 140 and they survive the transcription. That number, not a byte offset
and not a heading we invented, is what a reader can check against a printed
copy.

BUT HE NUMBERED LESS THAN HALF OF IT. MEASURED: 250 644 of the book's
467 kB of text -- more than half -- falls outside any numbered paragraph,
and thirteen chapters carry no number at all, sufixi.md (88 kB) and
vortordino.md among them. A first cut of this script keyed everything to
the numbers and therefore DROPPED ALL OF IT, including the one passage
where Beaufront argues against the accusative outright -- the very thing
the -n topic exists to surface.

So the unit here is THE BLOCK, one paragraph or note as the transcription
sets it, and the number is a LABEL the block carries when the book gives
it one. A block inside § 126 is cited « § 126 »; a block in an unnumbered
chapter is cited by its chapter and its rank in it. Every citation stays
checkable and nothing is out of reach.

    python3 tools/temi.py

Run it after tools/machine_readable.py: it reads chapitri/, which that
script writes.
"""

import re
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHAPTERS = ROOT / 'chapitri'
OUT = ROOT / 'temi'
SITE = 'https://ido.help/gramatiko/'

HEADER = '<!-- Generated by tools/temi.py from chapitri/. Do not edit. -->'

# A paragraph opens a LINE with its number, then a dash. Both dashes occur:
# § 93 is set with an en-dash where every other uses an em-dash, and a
# pattern admitting only the em-dash silently loses it.
#
# THE ANCHOR AT THE LINE START IS LOAD-BEARING. Relaxed to match anywhere,
# the pattern also catches the references to Progreso that the notes carry
# -- « decido : 428. — IV, 322 » -- and invents seven paragraphs the book
# does not have. Measured: 139 with the anchor, 146 without.
PARAGRAPH = re.compile(r'^(\d{1,3})\.\s*[—–]\s', re.M)

# THE TOPICS THAT HAVE NO CHAPTER. Anything the book gives a chapter to is
# already addressable and is only listed in the index; these are the ones
# whose paragraphs lie scattered. The terms are the book's own words.
TOPICS = [
    ('akuzativo', 'Akuzativo — la finalo « -n »',
     r'akuzativ|komplemento direta|inversig'),
    ('subjekto', 'Subjekto', r'subjekto'),
    ('komplemento', 'Komplemento', r'komplemento'),
    ('participo', 'Participo', r'particip'),
    ('infinitivo', 'Infinitivo', r'infinitiv'),
    ('pasivo', 'Pasivo', r'\bpasiv'),
    ('kondicionalo', 'Kondicionalo', r'kondicional'),
    ('imperativo', 'Imperativo', r'imperativ'),
    ('negado', 'Negado', r'\bnego\b|negativ|adverbo \*\*ne\*\*'),
]


def slug(t: str) -> str:
    s = unicodedata.normalize('NFD', t.lower())
    s = ''.join(c for c in s if unicodedata.category(c) != 'Mn')
    return re.sub(r'-{2,}', '-', re.sub(r'[^a-z0-9-]', '', s.replace(' ', '-')))


def blocks():
    """Every block of the book: its chapter, its rank, the § in force, its text.

    The § in force is the last number seen in that chapter, and None before
    the first -- which is the whole of thirteen chapters. The rank is the
    block's place in its chapter, counted from 1, and it is what makes an
    unnumbered block citable at all.
    """
    out = []
    for f in sorted(CHAPTERS.glob('*.md')):
        if f.name == 'index.md':
            continue
        t = f.read_text(encoding='utf-8')
        title = re.search(r'^# (.+)$', t, re.M)
        title = title.group(1) if title else f.stem
        body = t.split('\n---\n', 1)[1] if '\n---\n' in t else t
        current, rank = None, 0
        for b in body.split('\n\n'):
            b = b.strip()
            if not b:
                continue
            rank += 1
            m = PARAGRAPH.match(b)
            if m:
                current = int(m.group(1))
            out.append((current, f.name, title, rank, b))
    return out


def chapters():
    """The chapters, in the order the table gives them."""
    idx = (CHAPTERS / 'index.md').read_text(encoding='utf-8')
    return re.findall(r'\| \[([^\]]+)\]\(([^)]+)\) \|', idx)


def cite(n, title, fn, rank) -> str:
    """One block's address: the book's number where there is one."""
    if n is not None:
        return '## § %d — [%s](../chapitri/%s)' % (n, title, fn)
    return '## [%s](../chapitri/%s) — bloko %d (sen numero en la libro)' % (
        title, fn, rank)


def main() -> None:
    P = blocks()
    nums = sorted(n for n, _, _, _, _ in P if n is not None)
    absent = sorted(set(range(min(nums), max(nums) + 1)) - set(nums))
    opens = [int(PARAGRAPH.match(b[4]).group(1)) for b in P
             if PARAGRAPH.match(b[4])]
    twice = sorted({n for n in opens if opens.count(n) > 1})

    OUT.mkdir(exist_ok=True)
    for f in OUT.glob('*.md'):        # emptied, like the dictionary's vorti/
        f.unlink()

    written = []
    for name, title, pattern in TOPICS:
        rx = re.compile(pattern, re.I)
        hit = [b for b in P if rx.search(b[4])]
        if not hit:
            continue
        shown = ', '.join('`%s`' % t for t in pattern.split('|'))
        L = [HEADER, '', '# ' + title, '',
             'La bloki dil *Kompleta Gramatiko Detaloza* (L. de Beaufront, '
             '1925) qui traktas ica temo, quale li esas imprimita. La texto '
             'esas dil libro; la selekto dil termini serchata esas laboro dil '
             'sito.', '',
             'Termini serchata : %s — %d bloki.' % (shown, len(hit)), '',
             'Transskribita de ' + SITE, '', '---', '']
        last = None
        for n, fn, ti, rank, body in hit:
            head = cite(n, ti, fn, rank) if n is None else \
                '## § %d — [%s](../chapitri/%s)' % (n, ti, fn)
            if head != last:
                L += [head, '']
                last = head
            L += [body, '']
        (OUT / (name + '.md')).write_text('\n'.join(L), encoding='utf-8')
        written.append((name, title, len(hit)))

    L = [HEADER, '', '# Temi — Kompleta Gramatiko Detaloza', '',
         'Ek *Kompleta Gramatiko Detaloza di la Linguo Internaciona Ido*, '
         'L. de Beaufront, 1925.', 'Transskribita de ' + SITE, '',
         'Ica indexo donas adreso a la temi gramatikal. La citaji uzas la '
         'numeri dil paragrafi quin la libro ipsa imprimas.', '', '---', '',
         '## Temi qui transiras la chapitri', '',
         'Ca temi ne havas propra chapitro : lia paragrafi dis-esas en la '
         'libro. Singla dosiero kolektas li, kun lia numeri.', '',
         '| temo | bloki | dosiero |', '| --- | ---: | --- |']
    L += ['| %s | %d | [%s.md](%s.md) |' % (ti, n, nm, nm)
          for nm, ti, n in written]
    L += ['', '## La chapitri', '',
          'Ca temi havas propra chapitro, e la chapitro esas lia adreso.', '',
          '| chapitro | dosiero |', '| --- | --- |']
    L += ['| %s | [../chapitri/%s](../chapitri/%s) |' % (t, h, h)
          for t, h in chapters()]
    unnumbered = [b for b in P if b[0] is None]
    bytes_un = sum(len(b[4]) for b in unnumbered)
    chapters_un = sorted({b[2] for b in unnumbered
                          if not any(x[0] is not None and x[1] == b[1]
                                     for x in P)})
    L += ['', '## Pri la numeri dil paragrafi', '',
          'La libro numerizas %d paragrafi, de § %d a § %d, ma **ol ne '
          'numerizas omno** : %s bloki, %s okteti, ne portas numero, e %d '
          'chapitri havas nula numero. Pro to la citaji hike uzas la numero '
          'kande ol existas, e la chapitro kun la rango dil bloko kande ol '
          'ne existas.'
          % (len(set(nums)), min(nums), max(nums), f'{len(unnumbered):,}',
             f'{bytes_un:,}', len(chapters_un)), '',
          'Chapitri sen numero : %s.' % ', '.join(chapters_un), '',
          '', '']   # the count is filled in below, once the list is known
    quirks = len(absent) + len(twice)
    L[-1] = ('Un kozo savenda ante citar per numero :' if quirks == 1
             else '%d kozi savenda ante citar per numero :' % quirks)
    L.append('')
    if 28 in absent:
        L += ['- **§ 28 ne existas en la transskripturo.** La chapitro GRADI '
              'KOMPARALA, qua esas inter § 27 e § 29, ne portas numero.']
    if 32 in absent:
        L += ['- **§ 32 esas en la texto ma ne trovebla hike.** Lua numero '
              'esas glutinita a la fino dil antea alineo, en POSEDAL '
              'ADJEKTIVI E PRONOMI, do ol ne komencas lineo.']
    for n in twice:
        L += ['- **§ %d aparas du foyi**, ambe en ADVERBI. Citar « § %d » '
              'ne sufichas por indikar un de li.' % (n, n)]
    L += ['', 'La cetera numeri de %d a %d esas unika e kompleta.'
          % (min(nums), max(nums)), '']
    (OUT / 'index.md').write_text('\n'.join(L) + '\n', encoding='utf-8')

    total = sum(f.stat().st_size for f in OUT.glob('*.md'))
    print('  %d blocks over %d chapters' % (len(P), len(chapters())))
    print('  %d topic files + index, %s bytes' % (len(written), f'{total:,}'))
    for nm, ti, n in written:
        print('    %-14s %3d blocks' % (nm, n))
    print('  absent: %s   twice: %s' % (absent or 'none', twice or 'none'))


if __name__ == '__main__':
    main()
